### ISSUE TITLE
How do these Less imports work?

### ISSUE THREAD

**Issue by zeke** [atom/one-light-syntax#15]
I noticed that `/index.less` is referring to imports in a nested directory without specifying their path:

```less
@import 'editor';
@import 'language';
```

That's pretty neat.

Does Less automatically traverse the directory looking for those files? Is a directory named `/styles` given special treatment by Less? I perused the [Less documentation](http://lesscss.org/features/#import-directives-feature) but didn't see anything about this behavior.

**Comment by simurai** [comment]
I think the `/styles` is just a convention in Atom and not part of Less.

Maybe [this](https://github.com/atom/atom/blob/7d743827820969871e8724e6f353887a3ddfc105/src/theme-manager.coffee#L299) allows to skip the `/styles` to import other less files.

/cc @atom/feedback ?

**Comment by zeke** [comment]
Thanks @simurai! Pretty sure you're right. Tentatively closing.
