### ISSUE TITLE
ui-variable to set the tree view line height

### ISSUE THREAD

**Issue by svoop** [atom/one-light-syntax#4]
This theme is really great!

Would it be possible to add a ui-variable or a setting to decrease the line height in the tree view? There's a lot of whitespace between the lines which renders the tree view less useful than it could be.

![screen shot 2015-02-07 at 11 15 12](https://cloud.githubusercontent.com/assets/7255/6091741/a9eb5f48-aeba-11e4-9b11-cedafeef1d49.png)

**Comment by thedaniel** [comment]
I think this issue belongs on atom/one-light-ui actually!

**Comment by svoop** [comment]
Ouch, you're right, thanks for the hint!
