### ISSUE TITLE
TypeScript colon does not show up properly

### ISSUE THREAD

**Issue by ryanolsonx** [atom/one-light-syntax#44]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Opening a file in the typescript language with One Light Syntax Theme renders colon characters as a block of black.

### Steps to Reproduce

1. Open atom
2. Open a typescript file that contains an object literal with a colon
3. You should see the black block in your syntax

**Expected behavior:** colon to show up nicely

**Actual behavior:** You see colon as a black block

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.23.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Windows 10 OS

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

#### CSS

It looks as though the selector for the colon (in TypeScript) is `.syntax--meta.syntax--separator`. If I toggle off the background-color attribute, the issue goes away (I just don't want to keep this in my stylesheet forever -- especially needing to comment it out when I change themes).

**Current**
```css
.syntax--meta.syntax--separator {
    background-color: #373b41;
    color: #383a42;
}
```

**With Fix**
```css
.syntax--meta.syntax--separator {
    color: #383a42;
}
```

I would send a pull request, but I don't want to break any other highlights that this selector is addressing.

#### Screenshot
![image](https://user-images.githubusercontent.com/238929/33955259-2503d18a-dff8-11e7-8ccb-c58b211663ff.png)

**Comment by 50Wliu** [comment]
Fixed in #41, should already be available in Atom 1.24 beta.

**Comment by ryanolsonx** [comment]
Thanks!

**Comment by morhook** [comment]
Thanks a lot! Fixed problem for me too!
